"""'first'

Revision ID: 690e47c56684
Revises: 
Create Date: 2019-11-03 21:26:17.447259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '690e47c56684'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
